### ISSUE TITLE
`//` operator doesn't work on Perl 5.8

### ISSUE THREAD

**Issue by ikesyo** [utgwkk/Test2-Plugin-GitHub-Actions-AnnotateFailedTest#4]
- https://github.com/utgwkk/Test2-Plugin-GitHub-Actions-AnnotateFailedTest/blob/8729a939a45d6a5912091a2d7926c46dc59f9bfd/lib/Test2/Plugin/GitHub/Actions/AnnotateFailedTest.pm#L37-L38
- https://github.com/utgwkk/Test2-Plugin-GitHub-Actions-AnnotateFailedTest/blob/8729a939a45d6a5912091a2d7926c46dc59f9bfd/cpanfile#L1

**Comment by utgwkk** [comment]
:bow: I wrote a wrong version requirement for Perl runtime in cpanfile. It will be fixed with #5.

I also tried to make this module compatible with Perl 5.8 in #3, but `cpanm -L local --installdeps .` failed in a workflow of `windows-latest` with Perl 5.8.
ref: https://github.com/utgwkk/Test2-Plugin-GitHub-Actions-AnnotateFailedTest/pull/3/checks?check_run_id=794153229
